netty:
  boss: 1
  worker: 1
  timeout: 6000
  port: 8060
  portSalve: 18060
  host: 127.0.0.1

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: GMT+8

  data:
    redis:
      host: 127.0.0.1
      ssl: false
      timeout: 5000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /

jwt:
  secret: secret