version: '3'
services:
  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.11.13-management
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
