version: '3'
services:
  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.11.13-management
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
  mysql:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=test
      - TZ=Asia/Shanghai