# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Code Check

on:
  workflow_dispatch:
  push:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ github.workflow }}-test-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-test-

      - name: Run Docker Compose Environment
        run: |
          docker-compose -f docker/docker-compose-unittest.yml up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Test Spring project
        run: |
          gradle test

      - name: Stop Docker Compose Environment
        run: |
          docker-compose -f docker/docker-compose-unittest.yml down
